### ISSUE TITLE
Liquid Dupe

### ISSUE THREAD

**Issue by tterrag1098** [DoubleDoorDevelopment/TorchTools#5]
Right clicking a tool with a bucket in the right click slot places the liquid, but does not empty the bucket, effectively duping the liquid inside.

**Comment by itanshi** [comment]
Was this resolved? I still find it true as of TorchTools-1.7.10-1.2.0.26 and cauldron is installed.

**Comment by Claycorp** [comment]
Cauldron isn't supported. Also isn't reproducible in regular modded minecraft.
