### ISSUE TITLE
Bug: Bibliocraft (possibly others)

### ISSUE THREAD

**Issue by thisischrys** [DoubleDoorDevelopment/TorchTools#8]
Bibliocraft has toolracks, if I rightclick tools to put them in there, it will often not work with this mod installed. I think those are tile entities? Maybe it's a good idea to only use the tool if the target is a block, not a tile entity? Or some kind of config or blacklist for TARGETTED blocks.

**Comment by thisischrys** [comment]
removed mod, stopped caring

**Comment by Claycorp** [comment]
In the newest build an option was added to ignore TileEntities. Enable that and the problem will go away.
