### ISSUE TITLE
Make the default for disableTE true

### ISSUE THREAD

**Issue by blay09** [DoubleDoorDevelopment/TorchTools#9]
TorchTools breaks literally every mod that provides some kind of "right-click block with tool" functionality. Examples are Railcraft's Crowbar, JABBA Barrels, Storage Drawers, Bibliocraft.

There is a dupe glitch related to this, as the comment on the config mentions even. I don't see how it's sensible to have the default still be 'false'.

When do you ever place torches against tile entities anyways? You usually use this mod when mining. For the rare occasions where you want to place something against a tile entity, it's not worth it having all those other things broken.

Honestly removing the option altogether and *never* screwing with the tile entity right click would be my step of action, but please consider at least making the default value of this option true.

**Comment by dries007** [comment]
The reason this is not default, is because this option didn't used to exist. So to preserve functionality we opted for enabled by default and never thought about it again.
I see how this is undesirable, and it will be changed.
